# Generated by Django 5.0.7 on 2024-08-21 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_doctors_dep_name_alter_doctors_doc_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='dep_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.departments'),
        ),
    ]
